### ISSUE TITLE
Cannot run the MSBuild.exe piece

### ISSUE THREAD

**Issue by monk78anthony** [awslabs/aws-saml-adfs-cmdlet-sample#1]
Hi,
I am trying to use your code, but get an error.
This is the PS and AWS SDK I have
AWS Tools for Windows PowerShell
Version 3.1.30.0
Amazon Web Services SDK for .NET
Version 3.1.3.8

And this is the error.
"C:\AWSSAMLCredentials\AWSSAMLCredentials.sln" (default target) (1) ->
"C:\AWSSAMLCredentials\ClassLibrary1\AWSSAMLCredentials.csproj" (default target) (2) ->
(ResolveAssemblyReferences target) ->
  C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1605,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "AWSSDK". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\AWSSAMLCredentials\ClassLibrary1\AWSSAMLCredentials.csproj]

"C:\AWSSAMLCredentials\AWSSAMLCredentials.sln" (default target) (1) ->
"C:\AWSSAMLCredentials\ClassLibrary1\AWSSAMLCredentials.csproj" (default target) (2) ->
(CoreCompile target) ->
  AWSSAML.cs(30,7): error CS0246: The type or namespace name 'Amazon' could not be found (are you missing a using directive or an assembly reference?) [C:\AWSSAMLCredentials\ClassLibrary1\AWSSAMLCredentials.csproj]
  AWSSAML.cs(31,7): error CS0246: The type or namespace name 'Amazon' could not be found (are you missing a using directive or an assembly reference?) [C:\AWSSAMLCredentials\ClassLibrary1\AWSSAMLCredentials.csproj]
  AWSSAML.cs(32,7): error CS0246: The type or namespace name 'Amazon' could not be found (are you missing a using directive or an assembly reference?) [C:\AWSSAMLCredentials\ClassLibrary1\AWSSAMLCredentials.csproj]
  AWSSAMLUtils.cs(29,7): error CS0246: The type or namespace name 'Amazon' could not be found (are you missing a using directive or an assembly reference?) [C:\AWSSAMLCredentials\ClassLibrary1\AWSSAMLCredentials.csproj]
  AWSSAMLUtils.cs(30,7): error CS0246: The type or namespace name 'Amazon' could not be found (are you missing a using directive or an assembly reference?) [C:\AWSSAMLCredentials\ClassLibrary1\AWSSAMLCredentials.csproj]
  AWSSAMLUtils.cs(31,7): error CS0246: The type or namespace name 'Amazon' could not be found (are you missing a using directive or an assembly reference?) [C:\AWSSAMLCredentials\ClassLibrary1\AWSSAMLCredentials.csproj]
  AWSSAML.cs(210,47): error CS0246: The type or namespace name 'ImmutableCredentials' could not be found (are you missing a using directive or an assembly reference?) [C:\AWSSAMLCredentials\ClassLibrary1\AWSSAMLCredentials.csproj]
  AWSSAMLUtils.cs(103,16): error CS0246: The type or namespace name 'SessionAWSCredentials' could not be found (are you missing a using directive or an assembly reference?) [C:\AWSSAMLCredentials\ClassLibrary1\AWSSAMLCredentials.csproj]
    1 Warning(s)
    8 Error(s)

Any assistance so I can carry on testing is really appreciated.

Thanks!

**Comment by zoltak** [comment]
Hi,

Thanks for pointing this out. 

I've updated the HINT path in the C# Project File for the AWSSDK dependencies. 

The changes are in [commit a1e4ef4](https://github.com/awslabs/aws-saml-adfs-cmdlet-sample/commit/a1e4ef4d56d32466da3f5a20be9a09a0735931b3).

This should resolve your issue. If it doesn't please let me know.

Cheers,
Zoltak
